### ISSUE TITLE
Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine

### ISSUE THREAD

**Issue by i8sy72** [josephmcmac/XRM-Developer-Tool#205]
When importing a customization from excel if a user has Office x64 installed rather than x32 we get an error

_System.Exception: Error reading option sets from excel
   at JosephM.CustomisationImporter.Service.CustomisationImportService.ExtractOptionSetsFromExcel(String excelFile, LogController controller, CustomisationImportResponse response)
   at JosephM.CustomisationImporter.Service.CustomisationImportService.ReadExcel(CustomisationImportRequest request, LogController controller)
System.Exception: Error executing query from excel
File: Didasko HR.xlsx
Query: select * from ['Option Sets$']
System.InvalidOperationException: The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine.
   at System.Data.OleDb.OleDbServicesWrapper.GetDataSource(OleDbConnectionString constr, DataSourceWrapper& datasrcWrapper)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at JosephM.Spreadsheet.ExcelUtility.SelectFromExcel(String fileName, String query)
   at JosephM.Spreadsheet.ExcelUtility.SelectFromExcel(String fileName, String query)
   at JosephM.Spreadsheet.ExcelUtility.SelectPropertyBagsFromExcelTabName(String fileName, String tabName)
   at JosephM.CustomisationImporter.Service.CustomisationImportService.ExtractOptionSetsFromExcel(String excelFile, LogController controller, CustomisationImportResponse response)_

To fix this I had to rebuild as a x64 application along with AccessDatabaseEngine_X64.exe installed

**Comment by josephmcmac** [comment]
This error was thrown due to required drivers for querying the spreadsheet. It should not have been necessary to rebuild the application as 64 bit, you just need to have installed the relevant drivers for querying the excel files https://www.microsoft.com/en-us/download/confirmation.aspx?id=13255

If you know of a better way to query the Excel files which doesn't require these drivers please let me know, or perhaps there is a better connection string to use?

I may look at improving this at some stage, but not likely soon unless I quick fix is presented. For now it will just remain that the drivers need to get installed to use the features which read excel documents

**Comment by josephmcmac** [comment]
This is no longer an issue with the latest release as the code has been refactored to use Open Xml instead of the affected Sql drivers
